import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#111319',
        surface: '#111319',
        'surface-dim': '#111319',
        'surface-container-lowest': '#0c0e14',
        'surface-container-low': '#191b22',
        'surface-container': '#1e1f26',
        'surface-container-high': '#282a30',
        'surface-container-highest': '#33343b',
        'surface-bright': '#373940',
        'surface-variant': '#33343b',
        'on-surface': '#e2e2eb',
        'on-surface-variant': '#c7c4d7',
        'on-background': '#e2e2eb',
        primary: '#c0c1ff',
        'primary-container': '#8083ff',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary': '#1000a9',
        'on-primary-container': '#0d0096',
        secondary: '#a4c9ff',
        'secondary-container': '#0267b8',
        'secondary-fixed': '#d4e3ff',
        'secondary-fixed-dim': '#a4c9ff',
        'on-secondary': '#00315d',
        tertiary: '#4ae176',
        'tertiary-container': '#00a74b',
        'tertiary-fixed': '#6bff8f',
        'tertiary-fixed-dim': '#4ae176',
        'on-tertiary': '#003915',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        outline: '#908fa0',
        'outline-variant': '#464554',
        'inverse-surface': '#e2e2eb',
        'inverse-on-surface': '#2e3037',
        'inverse-primary': '#494bd6',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
} satisfies Config;
